2021-05-16 13:23:06,247 INFO: MyPR startup [in C:\Users\Justin\Desktop\gitProjects\MyPR\app\__init__.py:89]
2021-05-16 13:23:10,644 ERROR: Exception on /auth/login [GET] [in c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py:1441]
Traceback (most recent call last):
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Justin\Desktop\gitProjects\MyPR\app\auth\routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask_babel\__init__.py", line 689, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask_babel\__init__.py", line 682, in get_domain
    babel = current_app.extensions['babel']
KeyError: 'babel'
2021-05-16 13:23:13,220 ERROR: Exception on /auth/login [GET] [in c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py:1441]
Traceback (most recent call last):
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Justin\Desktop\gitProjects\MyPR\app\auth\routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask_babel\__init__.py", line 689, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask_babel\__init__.py", line 682, in get_domain
    babel = current_app.extensions['babel']
KeyError: 'babel'
2021-05-16 13:24:26,449 INFO: MyPR startup [in C:\Users\Justin\Desktop\gitProjects\MyPR\app\__init__.py:89]
2021-05-16 13:24:29,133 ERROR: Exception on /auth/login [GET] [in c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py:1441]
Traceback (most recent call last):
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Justin\Desktop\gitProjects\MyPR\app\auth\routes.py", line 27, in login
    return render_template('auth/login.html', title=('Sign In'), form=form)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\jinja2\environment.py", line 1067, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\jinja2\environment.py", line 996, in get_template
    return self._load_template(name, globals)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\jinja2\environment.py", line 957, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: auth/login.html
2021-05-16 13:27:30,445 INFO: MyPR startup [in C:\Users\Justin\Desktop\gitProjects\MyPR\app\__init__.py:89]
2021-05-16 13:28:00,437 ERROR: Exception on /auth/login [GET] [in c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py:1441]
Traceback (most recent call last):
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 2051, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1501, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Justin\Desktop\gitProjects\MyPR\app\auth\routes.py", line 27, in login
    return render_template('auth/login.html', title=('Sign In'), form=form)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\templating.py", line 150, in render_template
    ctx.app,
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\jinja2\environment.py", line 1289, in render
    self.environment.handle_exception()
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\jinja2\environment.py", line 924, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Justin\Desktop\gitProjects\MyPR\app\templates\auth\login.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Justin\Desktop\gitProjects\MyPR\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\Justin\Desktop\gitProjects\MyPR\app\templates\base.html", line 25, in block 'navbar'
    <li><a href="{{ url_for('index') }}">Home</a></li>
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\helpers.py", line 334, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\flask\helpers.py", line 322, in url_for
    endpoint, values, method=method, force_external=external
  File "c:\users\justin\desktop\gitprojects\mypr\venv\lib\site-packages\werkzeug\routing.py", line 2301, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
